routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\AdminController;
use App\Http\Controllers\RoomController;
use App\Http\Controllers\ImageUploadController;
use App\Http\Controllers\ClientController;
use App\Http\Controllers\GoogleController;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\PartnerController;
use App\Http\Controllers\AssetController;
use App\Http\Controllers\BookingController;
use App\Http\Controllers\PaymentController;
use App\Http\Controllers\TransactionController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', [ClientController::class, 'home'])->name('client.homepage');
Route::controller(AuthController::class)->group(function(){
    Route::post('/register', 'register')->name('register');
    Route::post('/login', 'login')->name('login');
    Route::get('/logout', 'logout')->name('logout');
});
Route::get('/booking', [ClientController::class, 'booking'])->name('client.booking');
Route::get('/booking/{id}/room', [ClientController::class, 'roomShow'])->name('client.booking.room');
Route::post('/booking', [ClientController::class, 'bookingStore'])->name('client.booking.store');

Route::middleware('client')->group(function () {
    Route::get('/bookings', [BookingController::class, 'bookings'])->name('client.booking.list');
    Route::get('/booking/{code}/payment', [PaymentController::class, 'viewPaymentBooking'])->name('client.booking.payment');
    Route::post('/booking/vnpay/payment', [PaymentController::class, 'checkout'])->name('client.booking.payment.vnpay');
    Route::get('/payment/return', [PaymentController::class, 'paymentRedirect'])->name('client.booking.payment.return');
    Route::get('/transactions', [TransactionController::class, 'indexClient'])->name('client.transactions.list');
});

Route::post('image/upload/store',[ImageUploadController::class, 'fileStore'])->name('upload.image');
Route::post('image/delete',[ImageUploadController::class, 'fileDestroy'])->name('delete.image');
Route::post('/get-image-update',[ImageUploadController::class, 'imageUpdateData'])->name('update.image.data');


Route::middleware('admin')->group(function () {
    Route::prefix('admin')->group(function () {
        Route::get('/', [AdminController::class, 'dashboard'])->name('admin.dashboard');

        Route::get('/clients', [AdminController::class, 'clients'])->name('admin.client.list');
        Route::get('/client/{id}/edit', [AdminController::class, 'activeOrInactiveUser'])->name('admin.client.edit');

        Route::get('/partners', [AdminController::class, 'partners'])->name('admin.partner.list');
        Route::get('/partner/{id}/edit', [AdminController::class, 'activeOrInactiveUser'])->name('admin.partner.edit');
        Route::get('/locations', [AdminController::class, 'locations'])->name('admin.location.list');
        Route::delete('/locations/{id}/delete', [AdminController::class, 'deleteLocation'])->name('admin.location.delete');

        Route::get('/assets', [AdminController::class, 'assets'])->name('admin.asset.list');
        Route::get('/asset-blocks', [AdminController::class, 'assetBlock'])->name('admin.asset.block.list');
        Route::get('/asset-restore/{id}', [AdminController::class, 'restoreAsset'])->name('admin.asset.restore');
        Route::delete('/assets/{id}', [AdminController::class, 'blockAsset'])->name('admin.asset.block');

        Route::get('/rooms', [AdminController::class, 'rooms'])->name('admin.room.list');
        Route::get('/room-blocks', [AdminController::class, 'roomBlock'])->name('admin.room.block.list');
        Route::get('/room-restore/{id}', [AdminController::class, 'restoreRoom'])->name('admin.room.restore');
        Route::delete('/rooms/{id}', [AdminController::class, 'blockRoom'])->name('admin.room.block');

        Route::get('/bookings', [AdminController::class, 'bookings'])->name('admin.bookings.index');
        Route::get('/transactions', [AdminController::class, 'transactions'])->name('admin.transactions.index');
    });
});

Route::middleware('partner')->group(function () {
    Route::prefix('partners')->group(function () {
        Route::get('/', [PartnerController::class, 'dashboard'])->name('partner.dashboard');
        Route::resource('rooms', RoomController::class);
        Route::resource('assets', AssetController::class);
        Route::get('/bookings', [BookingController::class, 'index'])->name('bookings.index');
    });
});

Route::controller(GoogleController::class)->group(function(){
    Route::get('auth/google', 'redirectToGoogle')->name('auth.google');
    Route::get('auth/google/callback', 'handleGoogleCallback');
});

app/Http/Controllers/AssetController.php
<?php

namespace App\Http\Controllers;

use App\Models\AssetModel;
use App\Models\DistrictModel;
use App\Models\ImageAssetModel;
use App\Models\ProvinceModel;
use App\Models\RoomModel;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class AssetController extends Controller
{
    protected $user;
    protected $asset;
    protected $room;
    protected $province;
    protected $district;
    protected $image;
    public function __construct(User $user, AssetModel $asset, RoomModel $room, ProvinceModel $province, DistrictModel $district, ImageAssetModel $image)
    {
        $this->user = $user;
        $this->asset = $asset;
        $this->room = $room;
        $this->province = $province;
        $this->district = $district;
        $this->image = $image;
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $title = 'List asset';
        $assets = $this->asset->where('user_id', Auth::id())->with('image')->orderBy('id')->paginate(1);
        return view('main.partner.assets.list', compact('assets','title'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $action = route('assets.store');
        $province = $this->province->get();
        $district = $this->district->get();
        $title = "Create asset";
        return view('main.partner.assets.create_or_update', compact('title','action', 'province', 'district'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        try {
            $assetStore = $this->asset->create([
                'name' => $request->name,
                'province' => $request->province,
                'district' => $request->district,
                'address' => $request->address,
                'user_id' => Auth::id(),
            ]);
            $this->image->create([
                "image_path" => uploadFile($request->image),
                "asset_id" => $assetStore->id
            ]);
            return redirect()->route('assets.index')->with('message', 'create asset success')->with('status', true);
        } catch (\Throwable $e) {
            return back()->with('message', $e)->with('status', false);
        }

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $title = "Update asset";
        $action = route('assets.update', $id);
        $method = 'put';
        $province = $this->province->get();
        $district = $this->district->get();
        $asset = $this->asset->find($id);
        return view('main.partner.assets.create_or_update', compact('title', 'action', 'province', 'district', 'asset', 'method'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        try {
            $this->asset->find($id)->update([
                'name' => $request->name,
                'province' => $request->province,
                'district' => $request->district,
                'address' => $request->address,
            ]);
            if ($request->image) {
                $this->image->where('asset_id', $id)->update([
                    "image_path" => uploadFile($request->image),
                ]);
            }
            return redirect()->route('assets.index')->with('message', 'update asset success')->with('status', true);
        } catch (\Throwable $e) {
            return back()->with('message', $e)->with('status', false);
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        try {
            $this->asset->find($id)->delete();
        } catch (\Throwable $e) {
            return back()->with('message', $e)->with('status', false);
        }

        return redirect()->route('assets.index')->with('message', 'remove asset success')->with('status', true);
    }
}

app/Http/Controllers/PartnerController.php
<?php

namespace App\Http\Controllers;

use App\Models\BookingModel;
use App\Models\RoomModel;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class PartnerController extends Controller
{
    protected $booking;
    protected $room;
    public function __construct(BookingModel $booking, RoomModel $room)
    {
        $this->booking = $booking;
        $this->room = $room;
    }
    public function dashboard()
    {
        $newBookings = $this->booking->where('status', PENDING)->with('room')
            ->whereHas('room', function ($query){
                $query->where('user_id', Auth::id());
            })
            ->get();
        $checkinBookings = $this->booking->where('start_date', 'like', '%'. Carbon::today()->toDateString() .'%')->with('room')
            ->whereHas('room', function ($query){
                $query->where('user_id', Auth::id());
            })
            ->get();
        $checkoutBookings = $this->booking->where('end_date', 'like', '%'. Carbon::today()->toDateString() .'%')->with('room')
            ->whereHas('room', function ($query){
                $query->where('user_id', Auth::id());
            })
            ->get();
        return view('main.partner.dashboard', compact('newBookings', 'checkinBookings', 'checkoutBookings'));
    }
}

resources/views/main/partner/assets/create_or_update.blade.php
@extends('layouts.main')
@section('title', $title)
@section('styles')
    <link rel="stylesheet" href="{{asset('main')}}/vendor/select2/css/select2.min.css">
    <link href="{{asset('main')}}/vendor/jquery-nice-select/css/nice-select.css" rel="stylesheet">
@endsection
@section('contents')
    <div class="row">
        <div class="col-xl-12 col-lg-12">
            <div class="card">
                <div class="card-header">
                    <h4 class="card-title">{{$title}}</h4>
                </div>
                <div class="card-body">
                    <div class="basic-form">
                        <form action="{{$action}}" method="post" enctype="multipart/form-data">
                            {{isset($method) ? method_field('PUT') : ""}}
                            @csrf
                            <div class="row mt-2">
                                <div class="col-xl-4 col-lg-4">
                                    @include('main.component.form.input',
                                        [
                                            'label' => 'Name',
                                            'id' => "name",
                                            'placeholder' => "Please enter name asset!",
                                            'type' => "text",
                                            'name' => "name",
                                            'value' => $asset->name ?? "",
                                        ]
                                    )
                                </div>
                                <div class="col-xl-4 col-lg-4">
                                    <div class="mb-3">
                                        <label class="fs-16 ms-1" for="single-select2">
                                           Province
                                            <span class="text-danger">*</span>
                                        </label>
                                        <select class="default-select form-control wide mb-3" id="single-select2" name="province">
                                            <option value="">Please choose an option!</option>
                                            @foreach($province as $item)
                                                <option value="{{$item->name}}" @if(isset($asset)) {{$asset->province == $item->name ? 'selected' : ''}} @endif>{{$item->name}}</option>
                                            @endforeach
                                        </select>
                                        @error('province')
                                        <p class="text-danger mt-1">{{ $message }}</p>
                                        @enderror
                                    </div>
                                </div>
                                <div class="col-xl-4 col-lg-4">
                                    <div class="mb-3">
                                        <label class="fs-16 ms-1" for="single-select">
                                            District
                                            <span class="text-danger">*</span>
                                        </label>
                                        <select class="default-select form-control wide mb-3" id="single-select" name="district">
                                            <option value="">Please choose an option!</option>
                                            @foreach($district as $item)
                                                <option value="{{$item->name}}" @if(isset($asset)) {{$asset->district == $item->name ? 'selected' : ''}} @endif>{{$item->name}}</option>
                                            @endforeach
                                        </select>
                                        @error('province')
                                        <p class="text-danger mt-1">{{ $message }}</p>
                                        @enderror
                                    </div>
                                </div>
                            </div>
                            <div class="row mt-2">
                                <div class="col-xl-12 col-lg-12">
                                    @include('main.component.form.textarea',
                                        [
                                            'label' => 'Address',
                                            'id' => "address",
                                            'placeholder' => "Please enter address!",
                                            'name' => "address",
                                            'value' => $asset->address ?? "",
                                        ]
                                    )
                                </div>
                            </div>
                            <div class="row mt-2">
                                <div class="col-xl-12 col-lg-12">
                                    <label for="id">
                                        Image
                                        <span class="text-danger">*</span>
                                    </label>
                                    <div class="input-group mb-3">
                                        <div class="form-file">
                                            <input type="file" id="image" name="image" class="form-file-input form-control">
                                        </div>
                                        <span class="input-group-text">Upload</span>
                                    </div>
                                </div>
                            </div>
                            <div class="row mt-4">
                                <div class="col-xl-4 col-lg-4">
                                    <button class="btn btn-success bg-primary">Save</button>
                                    <a href="{{route('rooms.index')}}" class="btn btn-dark">Cancel</a>
                                </div>
                            </div>

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@section('scripts')
    <script src="{{asset('main')}}/vendor/jquery-nice-select/js/jquery.nice-select.min.js"></script>
    <script src="{{asset('main')}}/vendor/select2/js/select2.full.min.js"></script>
    <script src="{{asset('main')}}/js/plugins-init/select2-init.js"></script>

@endsection

resources/views/main/partner/assets/list.blade.php
@extends('layouts.main')
@section('title', $title)
@section('styles')
    <link rel="stylesheet" href="{{asset('main')}}/vendor/toastr/css/toastr.min.css">
@endsection
@section('contents')
    <div class="row mt-4">
        <div class="col-xl-12">
            <div class="card">
                <div class="card-body p-0">
                    <div class="tab-content">
                        <div class="tab-pane active show" >
                            <div class="table-responsive">
                                <table class="table card-table display mb-4 shadow-hover default-table table-responsive-lg dataTable no-footer" id="guestTable-all">
                                    <thead>
                                    <tr>
                                        <th>Name</th>
                                        <th>Location</th>
                                        <th>Address</th>
                                        <th>Created at</th>
                                        <th class="bg-none">Action</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    @foreach($assets as $value)
                                    <tr>
                                        <td>
                                            <div class="room-list-bx d-flex align-items-center">
                                                <img class="me-3 rounded" src="{{$value->image[0]->image_path}}" alt="" style="object-fit: cover">
                                                <div>
                                                    <span class=" fs-16 font-w500 text-nowrap">{{$value->name}}</span>
                                                </div>
                                            </div>
                                        </td>
                                        <td>
                                            <div>
                                                <span class="font-w600 text-nowrap">
                                                    <i class="flaticon-381-location me-2"></i>
                                                    {{$value->province}}
                                                </span>
                                            </div>
                                        </td>
                                        <td class="job-desk3">
                                            <p>
                                                {{$value->address}}, {{$value->district}}, {{$value->province}}
                                            </p>
                                        </td>
                                        <td>
                                            <span class="font-w600 text-nowrap">{{timeAgo($value->created_at)}}</span>
                                        </td>
                                        <td class="text-nowrap">
                                            <form action="{{ route('assets.destroy',$value->id) }}" method="post">
                                                @csrf
                                                @method('DELETE')
                                                @if(checkRoom($value->id))
                                                    <button type="submit" class="btn btn-sm btn-danger">Delete</button>
                                                @endif
                                                <a href="{{route('assets.edit', $value->id)}}" class="btn btn-sm btn-warning">Update</a>
                                            </form>
                                        </td>
                                    </tr>
                                    @endforeach
                                    </tbody>
                                </table>
                                <div class="d-flex justify-content-between">
                                    <div class="dataTables_info" id="guestTable-all_info" role="status" aria-live="polite"></div>
                                    <div class="dataTables_paginate paging_simple_numbers">
                                        <nav>
                                            @include('main.component.pagination',['datas' => $assets])
                                        </nav>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@section('scripts')
    <script src="{{asset('main')}}/vendor/toastr/js/toastr.min.js"></script>
    <script src="{{asset('main')}}/js/plugins-init/toastr-init.js"></script>
    <script type="text/javascript">
        let message = '{{ session('message') }}'
        let status = '{{ session('status') }}'
        if(message) {
            if(status){
                toastr.success(message)
            }else {
                toastr.error(message)
            }
        }
    </script>
@endsection